/*
 * Generated by extract-headers.sh.
 */
#ifndef __ASM_ARM_CHECKPOINT_HDR_H_
#define __ASM_ARM_CHECKPOINT_HDR_H_

/*
 *  Checkpoint/restart - architecture specific headers ARM
 *
 *  Copyright (C) 2008-2010 Oren Laadan
 *  Copyright (C)      2010 Christoffer Dall
 *
 *  This file is subject to the terms and conditions of the GNU General Public
 *  License.  See the file COPYING in the main directory of the Linux
 *  distribution for more details.
 */

#include <linux/types.h>

/* ARM structure seen from kernel/userspace */

#define CKPT_ARCH_ID CKPT_ARCH_ARM

/* arch dependent constants */
#define CKPT_ARCH_NSIG 64
#define CKPT_TTY_NCC 8

struct ckpt_hdr_header_arch {
	struct ckpt_hdr h;
	__u32	cpu_architecture;
	__u8	mmu;		/* Checkpointed on mmu system */
	__u8	aeabi;		/* Checkpointed on AEABI kernel */
	__u8	oabi_compat;	/* Checkpointed on OABI compat. system */
} __attribute__((aligned(8)));

struct ckpt_hdr_thread {
	struct ckpt_hdr h;
	__u32		syscall;
	__u32		tp_value;
	__u32		thumbee_state;
} __attribute__((aligned(8)));

struct ckpt_hdr_cpu {
	struct ckpt_hdr h;
	__u32		uregs[18];
} __attribute__((aligned(8)));

struct ckpt_hdr_mm_context {
	struct ckpt_hdr h;
	__u32		end_brk;
} __attribute__((aligned(8)));



#endif /* __ASM_ARM_CHECKPOINT_HDR_H_ */
